export default function TermsAndConditions() {
  const sections = [
    {
      id: "service-overview",
      title: "1. Service Overview",
      content: `Adiyogi Cabz (operated by Vijay Tours & Travels) provides cab booking, airport transfers, outstation trips, rental vehicles, and holiday packages across Mysuru, Bengaluru, Coorg, Ooty, and surrounding regions. By accessing our website or using our AI assistant to place a booking, you agree to be bound by these Terms & Conditions. These terms apply to all users including passengers, visitors, and any third parties who interact with our platform.`,
    },
    {
      id: "booking-rules",
      title: "2. Booking Rules",
      content: `All bookings must be made through our website, AI assistant, or authorised contact channels. A booking is confirmed only after you receive a written or electronic confirmation from us. We reserve the right to decline any booking at our discretion. You must provide accurate pickup location, drop location, date, time, and passenger count. Providing false information may result in cancellation without refund. Bookings made less than 2 hours before the scheduled pickup are subject to driver availability and may not be guaranteed.`,
    },
    {
      id: "cancellation",
      title: "3. Cancellation & Refund Policy",
      content: `Cancellations made more than 24 hours before the scheduled pickup are eligible for a full refund. Cancellations made between 6 and 24 hours before pickup are eligible for a 50% refund. Cancellations made less than 6 hours before pickup are non-refundable. No-shows (passenger absent at pickup point) are non-refundable. Refunds, where applicable, will be processed within 5–7 business days to the original payment method. In cases of cancellation due to extreme weather, vehicle breakdown, or other force majeure events, we will offer a full reschedule or refund at our discretion.`,
    },
    {
      id: "passenger-responsibilities",
      title: "4. Passenger Responsibilities",
      content: `Passengers are responsible for being present at the agreed pickup point at the scheduled time. Adiyogi Cabz is not liable for missed pickups due to passenger delay. Passengers must not engage in behaviour that endangers the driver or other passengers, including consuming alcohol or illegal substances in the vehicle. Any damage caused to the vehicle by a passenger will be charged to the passenger at the cost of repair. Children must be accompanied by a guardian. Passengers are responsible for their personal belongings throughout the journey.`,
    },
    {
      id: "pricing",
      title: "5. Pricing",
      content: `All fares displayed on the platform are estimates unless explicitly confirmed at booking. Final fares may vary based on actual distance, waiting time, toll charges, state taxes, and fuel surcharges applicable at the time of travel. Outstation fares are quoted per kilometre and include a driver allowance for overnight trips. Airport transfer fares are fixed and include parking charges. We reserve the right to revise our pricing at any time without prior notice. Any pricing errors on the platform will be corrected before confirmation, and you will be notified of the revised fare.`,
    },
    {
      id: "driver-responsibilities",
      title: "6. Driver Responsibilities",
      content: `Our drivers are responsible for operating vehicles safely and within applicable traffic laws. Drivers are required to maintain a clean, well-maintained vehicle and present valid driving licences and vehicle permits at all times. Drivers must not use mobile phones while driving, must follow the agreed route unless instructed otherwise by the passenger, and must treat all passengers with courtesy and professionalism. Any driver misconduct should be reported to us immediately via our contact channels.`,
    },
    {
      id: "liability",
      title: "7. Liability",
      content: `Adiyogi Cabz is not liable for any loss, injury, or damage arising from delays due to traffic conditions, acts of nature, road closures, or circumstances beyond our reasonable control. Our total liability in any circumstance shall not exceed the amount paid for the specific booking in dispute. We are not responsible for any consequential, indirect, or incidental losses including missed flights, events, or appointments. We strongly recommend passengers carry adequate travel insurance for long-distance and outstation journeys.`,
    },
    {
      id: "ai-disclaimer",
      title: "8. AI Assistant Disclaimer",
      content: `Our AI assistant is provided as a convenience tool to help users explore services, get fare estimates, and initiate bookings. Responses generated by the AI are informational and should not be considered final confirmations unless explicitly verified by our team. Fare estimates provided by the AI are approximate and subject to change. Adiyogi Cabz is not liable for decisions made solely on the basis of AI-generated responses. The AI may occasionally produce inaccurate or incomplete information; always verify critical details with our support team before travel.`,
    },
    {
      id: "intellectual-property",
      title: "9. Intellectual Property",
      content: `All content on this website, including but not limited to text, graphics, logos, icons, images, and software, is the property of Vijay Tours & Travels and is protected under applicable copyright and intellectual property laws. You may not reproduce, distribute, modify, or create derivative works from any content on this platform without our prior written consent. Unauthorised use of our brand name, logo, or any proprietary content is strictly prohibited.`,
    },
    {
      id: "governing-law",
      title: "10. Governing Law",
      content: `These Terms & Conditions are governed by and construed in accordance with the laws of India. Any disputes arising out of or in connection with these terms shall be subject to the exclusive jurisdiction of the courts in Bengaluru, Karnataka. We encourage users to resolve disputes amicably by contacting our support team before pursuing legal remedies.`,
    },
    {
      id: "contact",
      title: "11. Contact Information",
      content: `If you have any questions, concerns, or complaints regarding these Terms & Conditions or our services, please contact us:\n\nEmail: vijaytourstravels6158@gmail.com\nPhone: +91 7022237255\nAddress: Bellandur, Bangalore, Karnataka, India\n\nWe aim to respond to all enquiries within 2 business days.`,
    },
  ];

  return (
    <div
      className="min-h-screen bg-white"
      style={{ fontFamily: "system-ui, -apple-system, sans-serif" }}
    >
      {/* Header */}
      <div className="border-b border-neutral-100 px-6 py-10 sm:px-10 lg:px-20">
        <div className="max-w-3xl">
          <p className="text-[11px] font-semibold uppercase tracking-[0.15em] text-neutral-400 mb-3">
            Legal
          </p>
          <h1 className="text-[32px] font-semibold tracking-tight text-neutral-950 leading-tight">
            Terms &amp; Conditions
          </h1>
          <p className="mt-2 text-[13.5px] text-neutral-400 leading-relaxed">
            Last updated: June 2025 &nbsp;·&nbsp; Vijay Tours &amp; Travels, Bengaluru
          </p>
          <p className="mt-4 text-[13.5px] text-neutral-500 leading-relaxed max-w-xl">
            Please read these terms carefully before using our services. By booking a ride or using our platform, you agree to these terms in full.
          </p>
        </div>
      </div>

      {/* Body */}
      <div className="max-w-3xl mx-auto px-6 sm:px-10 lg:px-0 py-12">

        {/* Table of contents */}
        <div className="mb-12 p-5 rounded-xl border border-neutral-100 bg-neutral-50">
          <p className="text-[11px] font-semibold uppercase tracking-[0.12em] text-neutral-400 mb-3">
            Contents
          </p>
          <ol className="flex flex-col gap-1.5">
            {sections.map((s) => (
              <li key={s.id}>
                <a
                  href={`#${s.id}`}
                  className="text-[12.5px] text-neutral-500 hover:text-neutral-900 transition-colors"
                >
                  {s.title}
                </a>
              </li>
            ))}
          </ol>
        </div>

        {/* Sections */}
        <div className="flex flex-col divide-y divide-neutral-100">
          {sections.map((s) => (
            <section key={s.id} id={s.id} className="py-8">
              <h2 className="text-[15px] font-semibold text-neutral-900 mb-3 tracking-tight">
                {s.title}
              </h2>
              {s.content.split("\n\n").map((para, i) => (
                <p key={i} className="text-[13.5px] text-neutral-500 leading-[1.75] mb-3 last:mb-0">
                  {para}
                </p>
              ))}
            </section>
          ))}
        </div>

        {/* Footer note */}
        <div className="mt-10 pt-8 border-t border-neutral-100">
          <p className="text-[12px] text-neutral-400 leading-relaxed">
            These terms were last reviewed in June 2025. Adiyogi Cabz reserves the right to update these terms at any time. Continued use of our services after any changes constitutes acceptance of the revised terms.
          </p>
        </div>
      </div>
    </div>
  );
}